### PR TITLE
add key-combination to quit m8c

### PR DESCRIPTION
**Pull request by maks**
This makes the select+start key combination generate a quit message, to exit m8c.

This is useful for people running m8c on handheld games consoles for example, where there is no other way to cleaniy exit m8c.

### CODE REVIEW

**Comment by maks** [comment]
@laamaa I'm not sure if this is the best key combination for this, but I wanted to keep the existing screen-refresh key combo available and was trying to come up with something that is not already used, that's not too easy to press accidentally while also not too hard to press either on a game controller pad.

**Comment by maks** [comment]
Doh, I just realised that this is of course the "Play song from current song position" shortcut, so I'll need to coem up with a diff unused key combination.

**Comment by bloopclick** [comment]
Maybe rather than using a key combo of existing buttons, the user could pick something that is on their controller but not mapped to m8 functions.

**Comment by maks** [comment]
@bloopclick yes I had originally planned to do just that, as on the Anbernic 351's that most people seem to be using there would be several unused ones to choose from. I'll amend this PR to do that I think,

**Comment by laamaa** [comment]
As you said previously yourself, start+sel is not a good idea since it's already in use by M8. I'm closing this PR as it isn't suitable in its current form and the discussion on a better way to implement this is already done. If you manage to find a way to set up a custom joypad button binding for quit that can be set via the config file, feel free to submit a new PR! :)

(PS. Sorryyyy, I needed to edit a commit that I had accidentally done with a work account earlier this week and it seems to have messed up the history a bit. Could you please clone the repo again and do your changes there?)

**Pull request closed without merging**
