### PR TITLE
add support for SDL_Joystick

### PR DESCRIPTION
**Pull request by yatli**

### CODE REVIEW

**Review by smootalicious — COMMENTED** [review]
Wouldn't it just be easier to define your device as a SDL game controller than to add all the generic joystick handling code?

**Comment by smootalicious** [comment]
I see what you are saying. Basically the joystick API is a superset of the GameController api. Defining the joystick as a gamecontroller in the gamecontroller DB would make it just work, but I understand that can be daunting. The code seems like it would work without negatively affecting anything. Unsure how it would affect performance.

**Comment by smootalicious** [comment]
To be more clear - I understand this is more of a pain than just having the generic joystick api code in place, but you can define the joystick for m8c to use by adding an entry in the gamecontroller db. You can use a tool to create the details of the entry - https://generalarcade.com/gamepadtool/

**Comment by yatli** [comment]
> Basically the joystick API is a superset of the GameController api

Yeah, I just realized that too. I used `sdl-jstest` to make sense of button ids, and in their code they treat everything as joysticks: https://github.com/Grumbel/sdl-jstest/blob/6d29d45a06b1b465fe5ee1779b80e1de8c37fff2/sdl2-jstest.c#L139

Perhaps we could do that too?

**Comment by smootalicious** [comment]
I made some changes in my fork that incorporates one of your changes - init the game controllers in main - that was a good catch. Also reading the database has to happen before assigning the joystick or it doesn't register as a gamepad. Check out my latest 3 commits in my fork.

**Comment by yatli** [comment]
Thanks for looking into the details, and this is a great summary!

**Comment by laamaa** [comment]
Thanks for the insights. In my opinion it probably would be a good idea to just fix the order that the game controller db is loaded before game controllers are initialized so custom mappings would be recognized properly (currently needs reconnecting), I'd rather not add many new features currently as I don't have much time for maintaining the project anyway :/

The readme could also probably be improved a bit on how the controller stuff works & how mappings should be made

**Comment by laamaa** [comment]
game controller db initialization changed in PR #77, probably don't want to add a sdl_joystick fallback for now.

**Pull request closed without merging**
